"use strict";this.default_PlayStoreUi=this.default_PlayStoreUi||{};(function(_){var window=this;
try{
_.rg(_.lpa);
_.u("sOXFj");
var axa=class extends _.er{H(a){return a()}};_.fr(_.kpa,axa);
_.w();
_.u("oGtAuc");
_.Rwa=new _.Me(_.lpa);
_.w();
var Swa;Swa=function(){var a=_.de();a=_.be(a,_.zda);if(!_.ae(a))return a};_.Twa=class extends _.cl{constructor(){super();this.soy=this.jk=null;if(this.Nk()){var a=_.kk(this.bi(),[_.fl,_.el]);a=_.Bf([a[_.fl],a[_.el]]).then(function(b){this.soy=b[0];this.jk=b[1]},null,this);this.Ne(a)}this.Oa=Swa()}Ne(a){_.dl(this,a)}An(a){return this.Oa.An(a)}getData(a){return this.Oa.getData(a)}iq(){_.mm(this.jk.Te())}dI(){}static [_.Re](){return!0}};_.Wr=(a,b)=>{a&&_.Oe.Fb().register(a,b)};
_.u("q0xTif");
var Vwa=function(a){const b=c=>{_.Zl(c)&&(_.Zl(c).oc=null,_.Er(c,null));c.XyHi9&&(c.XyHi9=null)};b(a);a=a.querySelectorAll("[c-wiz]");for(let c=0;c<a.length;c++)b(a[c])};var Wwa,Xwa,Ywa,Zwa;Wwa=function(a){const b=a.Xa();return(...c)=>a.Va.H(()=>b(...c))};Xwa=function(a){const b=a.V();return b?(...c)=>a.Va.H(()=>b(...c)):b};Ywa=function(a,b,c){const d=a.jk.H.H.createElement("div");a.Ia.V(d,b,c);return d.childNodes.length==1?d.firstChild:d};Zwa=function(a,b){const c=a.jk.H.H.createElement("view-header");c.style.display="none";const d=Xwa(a);b=a.ka()?b:{wa:a.na.getParams()};a.N()?a.Ia.V(c,d,b):(a=a.soy.ta(d,b),c.appendChild(a));return c};
_.Xr=class extends _.Twa{static Ka(){return{context:{K_:"FVxLkf"},service:{Rb:_.Ur,component:_.Mr,Q8:_.Rwa}}}constructor(a){super();var b=a.context.K_;this.na=b.eq;this.La=this.mb=this.ta=null;this.Ia=a.service.Rb;this.Va=a.service.Q8;a=this.na.V.then(c=>{this.ta=c;this.mb=this.na.id.va(c,this.na.getParams()).variant});b=b.hT.then(c=>{this.La=c});this.Ha=this.Ha.bind(this);this.Ne(_.Bf([a,b]))}H(){return""}N(){return!1}Aj(){return this.na}bx(){var a=_.Xa(this.La,this.Ha);a={wa:this.na.getParams(),
DZ:this.na.va,qa:{pX:!1,wa:this.na.getParams(),Wa:this.na.id.na,UH:this.na.sD,Ta:this.H(),jsdata:_.Ya(this.ta)},nb:a,ffa:this.mb};Object.assign(a,this.ta||{});Object.assign(a,this.na.H);Object.assign(a.qa,this.na.H);return a}Ha(a,b){return Array.isArray(a)?a.length!=1||(b=this.na.id.N()[b],b&&b.hd)?_.Ye(a,c=>c.bx()):a[0].bx():a.bx()}V(){return null}ka(){return!1}render(){var a=this.bx(),b=Wwa(this);b=this.N()?Ywa(this,b,a):this.soy.Fc(b,a);this.V()&&(a=Zwa(this,a),b.appendChild(a));(a=this.na.id.V())&&
a.length>0&&a.forEach(()=>{});this.na.rendered(b);return b}va(){return this.soy.N(Wwa(this),this.bx())}dI(a){var b=this.bx();const c=Wwa(this);Vwa(a);this.Ia.N(a,c,b);this.Aj().rendered(a);this.V()&&(b=Zwa(this,b),b=(new _.Jm(b)).Gc(),_.Wf(_.Yf(a).body,_.Uwa,b))}};_.Wr(_.Vr,_.Xr);
_.w();
_.ICa=_.B("yNB6me",[_.Vr]);
_.rDa=_.B("dfkSTe",[_.Vr]);
_.tDa=_.B("qqarmf",[_.Vr]);
_.vDa=_.B("FuzVxc",[_.Vr]);
_.yDa=_.B("I8lFqf",[_.Vr]);
var Gjc,Hjc,Ijc,Jjc,Kjc,Ljc,Mjc,Njc,Ojc,Pjc,w2,Qjc,Rjc,Sjc,Tjc,Ujc,Vjc,Wjc,Xjc,Yjc,Zjc,$jc,bkc,ckc,dkc,ekc,fkc,gkc,hkc,ikc,jkc,kkc;Gjc=class extends _.z{constructor(a){super(a)}Xb(){return _.J(this,2)}lc(a){return _.yi(this,2,a)}};Hjc=class extends _.z{constructor(a){super(a)}H(){return _.L(this,1)}N(){return _.L(this,2)}V(){return _.G(this,_.St,3)}};Ijc=class extends _.z{constructor(a){super(a)}};Jjc=class extends _.z{constructor(a){super(a)}Xb(){return _.J(this,1)}lc(a){return _.yi(this,1,a)}};
Kjc=[2,6,7];Ljc=[4,5];Mjc=class extends _.z{constructor(a){super(a)}};Njc=class extends _.z{constructor(a){super(a)}};Ojc=class extends _.z{constructor(a){super(a)}};Pjc=[2,3];w2=function(a){return _.K(a,Hjc,3,Pjc)};Qjc=function(a){a.ha("data-mt","8F6486BF-D2A5-410E-91C9-E13489332881")};Sjc=function(a){a.open("li","zX8WCb");a.W(Rjc||(Rjc=["role","separator"]));a.ha("class"," VfPpkd-StrnGf-rymPhb-clz4Ic");a.U();a.Da()};
Tjc=function(a,b){const c=_.rP(d=>{Qjc(d);_.uP()&&_.sP(d,_.pP())});_.BP(a,b,!1,!1,void 0,"VfPpkd-rymPhb-Abojl jDawJf",c)};Ujc=function(a,b,c){c="VfPpkd-rymPhb-Abojl"+(c?" "+c:"");const d=_.rP(e=>{Qjc(e);_.uP()&&_.sP(e,_.pP())});_.CP(a,b,void 0,c,d)};_.akc=class extends _.z{constructor(a){super(a)}};
jkc=function(a){a.open("div","XmLLac");a.W(fkc||(fkc=["class","pib0Be"]));a.U();a.ua("a","pMmnn");a.W(gkc||(gkc="href https://policies.google.com/privacy target _blank class Afmgcd".split(" ")));a.U();a.text(_.O("隐私权政策"));a.close();a.ua("span","oJDiv");a.W(hkc||(hkc=["class","j55CI"]));a.U();a.text(" \u2022 ");a.close();a.ua("a","JkHYte");a.W(ikc||(ikc="href https://myaccount.google.com/termsofservice target _blank class Afmgcd".split(" ")));a.U();a.text(_.O("服务条款"));
a.close();a.Da()};
kkc=function(a,b,c,d,e,f){const g=a.Zv,h=a.Bs,k=_.bp(f??e);_.pY(b,{wa:c,qa:d,jscontroller:"IJGqxf",jsaction:"FzgWvd:fmKhsb;iFFCZc:nixEK;",body:_.Z(m=>{m.open("div","Kg4Xbd");m.U();var n=_.RX(g?.H())??_.RX(w2(k)?.V())??"";const q=_.EO(n,_.iO(_.qO(_.pO(_.oO(_.jO(new _.rO,!0),!0),!0),!0),32)),t=_.EO(n,_.iO(_.qO(_.pO(_.oO(_.jO(new _.rO,!0),!0),!0),!0),64)),v=_.rP(E=>{E.ha("srcset",q+" 1x, "+t+" 2x")}),x=g==null;n=_.rP(E=>{E.ha("jslog","219258; 1:3160; track:impression,click")});const y=_.Z(E=>{const A=
_.Z(Y=>{q?(Y.O("fH8Dkf"),_.Cib(Y,q,"VfPpkd-kBDsod WrEZCd",v)):(Y.O("JfQXie"),_.RP(Y,"account_circle","AX0y7c"));Y.T()});var H="";if(w2(k)){var M="Google 账号\uff1a"+(x?w2(k)?.H():_.bp(g).getName()??"")+" ("+(x?w2(k)?.N():h??"")+")";H+=M}else H+="打开账号菜单";M=_.rP(Y=>{_.HP(Y);_.sP(Y,_.pP(""))});E.O("v3zBHc");_.QP(a,E,H,A,q?"PeWVCc":"",void 0,void 0,void 0,M,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,!0);E.T()}),D=_.Z(E=>{const A=_.Z(H=>{if(w2(k)){H.open("div",
"anSVp");H.W(bkc||(bkc=["class","YQy4vd"]));H.U();H.ua("img","JuPYVb");H.W(ckc||(ckc=["class","jCQ2Zb"]));H.ha("src",_.np(q));_.sP(H,_.pP(v));H.ha("alt","个人资料");H.U();H.close();H.ua("div","r9Haqd");H.U();H.ua("div","luoiVb");H.W(dkc||(dkc=["class","ItxEje"]));H.U();H.print(x?w2(k)?.H():_.bp(g).getName()??"");H.close();H.ua("div","Fo0hbe");H.W(ekc||(ekc=["class","JauZY"]));H.U();H.print(x?w2(k)?.N():h??"");H.close();H.close();H.close();var M=_.rP(ia=>{ia.ha("data-href",""+_.RX(_.G(_.G(w2(k),
Gjc,4),_.St,1)));ia.ha("data-target","_blank")});H.O("BxaO9");_.FP(H,_.L(_.G(w2(k),Gjc,4),2),void 0,void 0,"BYi1pe",void 0,M);H.T()}else if(_.K(k,Ojc,2,Pjc)){M=_.Z(ia=>{const Ea=_.Z(qa=>{qa.O("lND1fc");qa.open("svg","SRyYyc");qa.W(Vjc||(Vjc="xmlns;http://www.w3.org/2000/svg;height;24px;viewBox;0 0 24 24;width;24px".split(";")));qa.U();qa.ua("path","aZXvD");qa.W(Wjc||(Wjc=["d","M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z",
"fill","#4285F4"]));qa.U();qa.close();qa.ua("path","fQ4GJb");qa.W(Xjc||(Xjc=["d","M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z","fill","#34A853"]));qa.U();qa.close();qa.ua("path","hsDDD");qa.W(Yjc||(Yjc=["d","M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z","fill","#FBBC05"]));qa.U();qa.close();qa.ua("path","oRRIIb");qa.W(Zjc||(Zjc=
["d","M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z","fill","#EA4335"]));qa.U();qa.close();qa.ua("path","OyygD");qa.W($jc||($jc=["d","M1 1h22v22H1z","fill","none"]));qa.U();qa.close();qa.Da();qa.T()});ia.O("NY8Lqf");Ujc(ia,Ea);ia.T()});var Y=_.rP(ia=>{ia.ha("data-href",""+_.RX(_.G(_.K(k,Ojc,2,Pjc),_.St,1)));ia.ha("data-add-continue-url-param","true")});H.O("I5j07c");_.FP(H,"使用 Google 账号登录",
M,void 0,void 0,void 0,Y);H.T()}M=_.Rh(_.G(k,Njc,1),Mjc,1,_.Lh());Y=M.length;for(let ia=0;ia<Y;ia++){var ta=M[ia];H.Dd("ZKG7xe-"+ia);Sjc(H);H.Md();ta=_.Rh(ta,Jjc,1,_.Lh());const Ea=ta.length;for(let qa=0;qa<Ea;qa++){const Fa=ta[qa],Ta=_.Z(Eb=>{if(_.L(Fa,_.Gh(Fa,Kjc,6))){Eb.O("mgNgod");var Kb=_.L(Fa,_.Gh(Fa,Kjc,6));Tjc(Eb,Kb);Eb.T()}else _.uP(_.QX(_.K(Fa,_.au,7,Kjc)))&&(Eb.O("JST16c"),Kb=_.QX(_.K(Fa,_.au,7,Kjc)),Ujc(Eb,Kb,"JyVPdd"),Eb.T())}),Na=_.rP(Eb=>{Eb.ha("data-href",""+_.RX(_.G(Fa,_.St,3)));
_.ni(Fa,11)&&Eb.ha("data-navigation","server");_.ni(Fa,9)&&Eb.ha("data-add-continue-url-param","true");_.G(Fa,Ijc,10)&&_.ri(_.G(Fa,Ijc,10),1)&&Eb.ha("jslog","178829; 1:"+_.ri(_.G(Fa,Ijc,10),1)+"; track:click,impression;")});H.Dd("lpA9lb-"+ia+"-"+qa);_.FP(H,_.L(Fa,1),Ta,_.ni(Fa,8)?_.YN(_.pi(Fa,_.Gh(Fa,Ljc,5))):"",void 0,"ffeky",Na);H.Md()}}H.O("QifnKb");Sjc(H);H.T();H.O("yrdMLb");jkc(H);H.T()});E.O("nV3rn");_.EP(a,E,A,"账号菜单","ydGPV","Ll1HQd",void 0,void 0,!0,void 0,!0);E.T()});
m.O("PSDvFc");_.GP(a,m,y,D,void 0,void 0,!0,n);m.T();m.close()})})};_.lkc=function(a,b,c){kkc(c??{},a,b.wa,b.qa,b.W1,b.X1)};_.lkc.Fa=_.P;_.mkc=()=>({variant:null,Sa:[],Ua:{}});var x2=class extends _.z{constructor(a){super(a)}};x2.prototype.oa="NUAMvf";new _.C(x2);new _.C(_.Fx);_.Mn.EkPGVc=_.Ln;var nkc=new _.ue("Qu3lde",_.Fx,x2,[_.Xj,!0,_.Yj,"/PlayStoreDataService.GetProfileMenuInfo"]);var okc,pkc;okc=function(a,b,c){a=c||{};b=a.Na||"rpc";c=new x2;var d={fatal:!1,Lc:["ptiYyf"],Ab:[{key:_.sr,value:new _.JC},{key:_.tr,value:new _.JC}]};let e;for(e in a)d[e]=a[e];return{qb:nkc,Na:b,yb:c,metadata:d}};pkc=function(a,b,c){a=c||{};b=a.Na||"rpc";c=new x2;_.si(c,2,!0);var d={fatal:!1,Lc:["h23ySe"],Ab:[{key:_.sr,value:new _.JC},{key:_.tr,value:new _.JC}]};let e;for(e in a)d[e]=a[e];return{qb:nkc,Na:b,yb:c,metadata:d}};
_.qkc=_.BA({Wa:!1,name:"vWsi9c",Ta:_.ICa,params:{ctor:_.akc},ab:[],data:{W1:okc,Wga:_.IC(okc),X1:pkc,Xga:_.IC(pkc)},Za:_.mkc,Ya:{},children:{}});
_.Tnc=class extends _.z{constructor(a){super(a)}H(){return _.hi(this,1,1)}N(){return _.ei(this,2)}};_.Unc=()=>({variant:null,Sa:[],Ua:{}});_.Vnc=_.BA({Wa:!0,name:"JfmpUc",Ta:_.tDa,params:{ctor:_.Tnc},ab:[],data:{zn:function(){}},Za:_.Unc,Ya:{},children:{}});
var Xnc,Ync,Znc,$nc,aoc,boc,coc,doc,eoc,foc,goc,hoc,ioc,joc,koc,loc,moc,noc,ooc,poc,qoc;_.Wnc=class extends _.z{constructor(a){super(a)}};aoc=function(){return"搜索应用和游戏"};
koc=function(a,b,c,d,e,f){b.open("div","ifJdEe");b.ha("class",e?"fWLDob":"FfLSic");b.U();f?(b.open("div","oYlzzd"),b.W(goc||(goc=["class","VnJy5c"])),b.U(),b.O("ZnOmob"),_.TX(a,b,32,32,void 0,f,"OWBiB",!0),b.T(),b.close(),b.open("div","lSvrVd"),b.W(hoc||(hoc=["class","qfH6Df"])),b.U(),b.print(c),b.print(d)):(b.open("div","Nuomkb"),b.W(ioc||(ioc=["class","VnJy5c"])),b.U(),b.O("nC7Kb"),_.BP(b,e?"history":"search",void 0,void 0,void 0,"dbAtlf"),b.T(),b.close(),b.open("div","aApfD"),b.W(joc||(joc=["class",
"qfH6Df"])),b.U(),b.print(c));b.close();b.Da()};
ooc=function(a,b,c,d,e,f,g,h,k,m,n,q){b.open("li","iq92vb");b.W(eoc||(eoc="class,YVhSle,role,option,jsaction,click:yaxEMb; mouseover:KC7Teb; mouseleave:n7h1o;,jsname,ldDtVd".split(",")));b.ha("id",h+"-"+g);b.ha("data-display-text",c+d+e);b.ha("data-index",""+g);b.ha("aria-selected",""+f);b.U();f=_.Z(t=>{const v=_.Z(y=>{y.O("FriyHb");y.open("div","zilhs");y.W(loc||(loc=["class","WuMlDe"]));y.U();y.print(c);y.ua("b","PwmUBd");y.W(moc||(moc=["class","XPmdRc"]));y.U();y.print(d);y.close();y.print(e);
y.Da();y.T()}),x=_.Z(y=>{y.O("YC9t9b");y.open("div","hZIixf");y.W(noc||(noc=["class","oWSyie"]));y.U();n!=null&&(y.print(n),y.O("yddLM"),_.BP(y,"star_rate",void 0,void 0,void 0,"sRzXp"),y.T());y.Da();y.T()});t.O("qo89v");koc(a,t,v,x,k,m);t.T()});q?(g=_.rP(t=>{t.ha("tabindex","-1")}),b.O("LBcuad"),_.q1(b,{navigation:q,Ba:"QTWoUe",content:f,attributes:g},a),b.T()):b.print(f);b.open("div","E7TWR");b.W(foc||(foc="class,NGOzcb,jsaction,click:gb9M9; mousedown:iZIFgc; touchstart:iZIFgc;,jsname,Ir3x4c".split(",")));
b.ha("data-display-text",c+d+e);b.U();b.O("iEgyNd");_.BP(b,"north_west",void 0,void 0,void 0,"UzumSc");b.T();b.close();b.Da()};
poc=function(a,b){const c=this.xd;var d=this.H;const e=this.ka,f=this.N,g=this.V;var h=this.na,k=b.Vs;const m=b.je;b=_.cO();a.open("div","Kyi96e");a.W(Xnc||(Xnc="jsaction click:mLt3mc;rcuQ6b:YOF2ad;qako4e:YOF2ad;kT0ch:s8Aiuc role combobox aria-haspopup listbox".split(" ")));a.ha("class","hQnXo"+(d?" sMVRZe":""));a.ha("jscontroller","q0NEmc");a.ha("aria-expanded",""+d);d&&a.ha("aria-controls",b);d&&a.ha("aria-owns",b);a.U();a.O("sUrs2b");a.open("div","dIu99");a.U();a.ua("label","sndXrf");a.W(Ync||
(Ync=["class","ePyrDc"]));a.U();a.ua("div","B6vHxd");a.W(Znc||(Znc=["class","j1R2Me"]));a.U();a.O("D2efMc");_.BP(a,"search",void 0,void 0,void 0,"Ic6Vy");a.T();a.close();a.ua("div","vrScbe");a.W($nc||($nc="class UJwHBc jsname t9v86 jsaction click:m8lR2c;".split(" ")));a.U();a.O("y7lmnb");_.BP(a,"west",void 0,void 0,void 0,"opB26b");a.T();a.close();let n="";switch(k){case 1:n+=aoc();break;case 9:k="";k=m?.H()?k+"搜索电影和电视节目":k+"搜索电影";n+=
k;break;case 5:n+="搜索\u56fe书";break;default:n+=aoc()}k=n;a.ua("input","Hh4asb");a.W(boc||(boc="class{HWAcU{jsname{oA4zhb{jsaction{input:atZ8Pd; click:mLt3mc,quipkb; keydown:duASZc{autocomplete{off{aria-autocomplete{list{type{text".split("{")));a.ha("aria-label","在 Google Play 中搜索");g>=0&&a.ha("aria-activedescendant",b+"-"+g);a.ha("placeholder",k);a.U();a.close();h!=null&&h.length>0&&(a.open("div","ZN6Dbd"),a.W(coc||(coc="class XLWCmc jsname YQKB2b jsaction click:jiNRsc;".split(" "))),
a.U(),a.O("X2CH6c"),_.BP(a,"clear",void 0,void 0,void 0,"VFjhDf"),a.T(),a.close());a.close();a.Da();a.T();if(d){a.O("Ag8Jv");a.open("ul","VtAogf");a.W(doc||(doc=["class","H3UN0","role","listbox"]));a.ha("id",b);a.U();d=e.length;for(h=0;h<d;h++)k=e[h],a.O("c9Ybp"),ooc(c,a,k.prefix,k.match,k.Vi,h===g,h,b,!0),a.T();d=f.length;for(h=0;h<d;h++)k=f[h],a.O("iztnZb"),ooc(c,a,k.prefix,k.match,k.Vi,h+e.length===g,h+e.length,b,!1,_.G(k.Vv,_.Ut,2),_.Jh(k.Vv,10)??void 0,k.Vv.Qb()),a.T();a.Da();a.T()}a.Da()};
qoc=function(a,b,c,d,e){_.pY(b,{Ba:"QvOuef",wa:c,qa:d,body:_.Z(f=>{f.O("oxorXb");var g={Vs:_.hi(c,1,1),je:e};f.Zb(_.Mmc,"Kyi96e","div",g,a,poc);f.T()})})};_.roc=function(a,b,c){qoc(c,a,b.wa,b.qa,b.je)};_.roc.Fa=_.P;_.soc=()=>({variant:null,Sa:[],Ua:{}});var toc;toc=function(a,b,c){a=c||{};b=a.Na||"rpc";c=new _.zF;var d={fatal:!1,Ab:[{key:_.sr,value:new _.JC},{key:_.tr,value:new _.JC}]};let e;for(e in a)d[e]=a[e];return{qb:_.AF,Na:b,yb:c,metadata:d}};_.uoc=_.BA({Wa:!1,name:"OhtnEd",Ta:_.vDa,params:{ctor:_.Wnc},ab:[],data:{je:toc,SD:_.IC(toc)},Za:_.soc,Ya:{},children:{}});
var woc;_.voc=class extends _.z{constructor(a){super(a)}};woc=function(a,b,c,d,e){_.pY(b,{wa:c,qa:d,body:_.Z(f=>{f.O("kJSOLb");_.Klc(a,f,e.H(),_.hi(c,1,1));f.T()})})};_.xoc=function(a,b,c){woc(c,a,b.wa,b.qa,b.zn)};_.xoc.Fa=_.P;_.yoc=()=>({variant:null,Sa:[],Ua:{}});_.zoc=_.BA({Wa:!0,name:"qJGTve",Ta:_.yDa,params:{ctor:_.voc},ab:[],data:{zn:function(){}},Za:_.yoc,Ya:{},children:{}});
_.u("dfkSTe");
_.B2.prototype.H=_.r(468,function(){return _.ei(this,3)});var Aoc=function(a,b){_.Ai(a,1,b)},Boc=function(a,b){_.si(a,2,b)},Coc=function(a,b){_.Ai(a,1,b)},Doc=class extends _.z{constructor(a){super(a)}getId(){return _.hi(this,1,1)}zc(){return _.ri(this,1)}Qb(){return _.G(this,_.Yt,2)}Ga(){return _.J(this,3)}Ja(){return _.L(this,3)}};Doc.prototype.oa="c7uwzc";var Eoc=class extends _.z{constructor(a){super(a)}H(){return _.Rh(this,Doc,1,_.Lh())}};Eoc.prototype.oa="tjNwSb";
var Foc,Goc,Hoc,Ioc,Joc=function(a,b,c,d,e,f,g){b.open("div","jMdBnf");_.sP(b,_.pP(d));b.U();d=_.Z(k=>{k.O("MmT8u");_.BP(k,e,void 0,void 0,void 0,"r9optf");k.T()});const h=_.rP(k=>{g&&_.sP(k,_.pP(""))});b.O("z7kyrc");_.QP(a,b,c,d,void 0,void 0,f,void 0,h,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,!0);b.T();b.Da()},Koc=function(a,b){const c=_.rP(d=>{d.ha("jscontroller","IcVnM");d.ha("jsaction","rcuQ6b:ewIngf;JIbuQc:L1KARc")});Joc(b,a,"帮助中心",c,"help_outline",
!0,"helpButton")},Loc=function(a,b){const c=_.rP(d=>{d.ha("jsaction","JIbuQc:bWGA9c;")});Joc(b,a,"搜索",c,"search",void 0,"searchButton")},Moc=function(a,b){const c=this.xd;var d=this.H,e=b.wa;b=b.nb;a.open("header","saioed");a.W(Goc||(Goc=["jsaction","rcuQ6b:npT2md;KwkHzf:IPLOJd;tGMTLb:T1PkR;","role","banner"]));a.ha("class","S3WLMd"+(d?" QKrU5e":""));a.ha("jscontroller","ArluEf");a.U();a.ua("nav","iT61ie");a.W(Hoc||(Hoc=["class","oPjgQb"]));a.ha("aria-label","页面标题");
a.U();a.O("ZS1W6b");d=_.hi(e,4,0);var f=_.hi(e,6,0),g=_.RX(_.G(e,_.St,7));const h=(0,_.Xo)("/store/games");a.open("a","NX4XQb");a.ha("href",_.mp(g??h));a.ha("aria-label","Google Play 徽标");a.ha("class","f0UV3d"+(d===2?" SwliHe":""));a.U();a.O("ZMSRTb");_.ep("Da",f)(a,null,c);a.T();a.Da();a.T();a.O("tFT7I");d=_.hi(e,2,0);f=_.hi(e,4,0);switch(d){case 1:f!==1&&(a.O("yCPj9"),_.xoc(a,b.dJ,c),a.T());break;case 2:a.O("pVWWoe"),_.roc(a,b.iQ,c),a.T()}a.T();a.O("VRSFXb");d=_.hi(e,2,0);a.open("div",
"xnSAue");a.W(Ioc||(Ioc=["class","oc9n0c"]));a.U();d!==0&&(d!==2&&d!==3&&(a.O("htcYpe"),Loc(a,c),a.T()),a.O("RvEUXb"),Koc(a,c),a.T());a.O("HzPIS");_.lkc(a,b.GK,c);a.T();a.Da();a.T();a.close();a.O("QJiTm");e={Im:_.hi(e,4,0),Pm:b.Pm};_.ep("Ba")(a,e,c);a.T();a.Da()},Noc=function(a,b,c,d,e){const f=_.rP(g=>{g.ha("id","kO001e")});_.pY(b,{wa:c,qa:d,attributes:f,body:_.Z(g=>{g.O("T2hYfb");var h={Im:_.hi(c,4,0),Pm:e.Pm};_.ep("Ca")(g,h,a);g.T();g.O("GF4ZMd");g.Zb(_.jnc,"saioed","header",{wa:c,nb:e},a,Moc);
g.T();g.O("CUNjjc");g.open("div","MC0Chf");g.W(Foc||(Foc=["jsaction","o3VKB:eQqUMb"]));g.ha("jscontroller","BfdUQc");g.U();g.Da();g.T()})})},Ooc=function(a,b,c){Noc(c,a,b.wa,b.qa,b.nb)};Ooc.Fa=_.P;var Poc=function(a,b,c){const d=c.LX;b.wa.H()||d?.H()==null||(a.O("zzI2Pe"),_.y2(c,a,d.H()),a.T())};Poc.Fa=_.P;var Qoc={GK:{},Pm:{zn:a=>a&&a.zn||void 0},iQ:{},dJ:{zn:a=>a&&a.zn||void 0}};var Roc=class extends _.z{constructor(a){super(a)}};Roc.prototype.oa="OG6gu";new _.C(Roc);new _.C(Eoc);_.Mn.tjNwSb=_.Ln;_.V(Eoc,Doc,function(a){return a.H()});var Soc=new _.ue("T6C6Se",Eoc,Roc,[_.Xj,!0,_.Yj,"/PlayStoreDataService.GetCorpusMenuDetail"]);var Toc=_.BA({Wa:!0,name:"BHlSfb",Ta:_.rDa,params:{ctor:_.B2},ab:[],data:{zn:function(a,b,c){a=c||{};b=a.Na||"rpc";c=new Roc;var d={fatal:!0,Ab:[{key:_.sr,value:new _.JC},{key:_.tr,value:new _.JC}]};let e;for(e in a)d[e]=a[e];return{qb:Soc,Na:b,yb:c,metadata:d}}},Za:()=>({variant:null,Sa:[],Ua:{GK:_.mkc,Pm:_.Unc,iQ:_.soc,dJ:_.yoc}}),Ya:Qoc,children:{GK:{id:_.qkc,name:"T8odlb",hb:function(){return{wa:new _.akc,id:_.qkc,name:"T8odlb"}}},Pm:(()=>{const a=Qoc.Pm;return{id:_.Vnc,name:"Exs87c",Ma:a,hb:function(b,
c,d){c=new _.Tnc;_.Dp(b,5)&&Boc(c,_.ei(b,5));_.eu(b,1)&&Aoc(c,_.hi(b,1,1));return{wa:c,id:_.Vnc,name:"Exs87c",Ma:a,wb:function(){return d.then(function(e){let f={};for(let g in a)f[g]=a[g](e);return f})}}}}})(),iQ:{id:_.uoc,name:"X6qTxd",hb:function(a){var b=new _.Wnc;_.eu(a,1)&&(a=_.hi(a,1,1),_.Ai(b,1,a));return{wa:b,id:_.uoc,name:"X6qTxd"}}},dJ:(()=>{const a=Qoc.dJ;return{id:_.zoc,name:"cCuJ4",Ma:a,hb:function(b,c,d){c=new _.voc;_.eu(b,1)&&Coc(c,_.hi(b,1,1));return{wa:c,id:_.zoc,name:"cCuJ4",Ma:a,
wb:function(){return d.then(function(e){let f={};for(let g in a)f[g]=a[g](e);return f})}}}}})()}});_.Wr(_.rDa,class extends _.Xr{constructor(a){super(a.Aa)}H(){return"dfkSTe"}N(){return!0}Xa(){return Ooc}V(){return Poc}});_.Br.dfkSTe=Toc;
_.w();
}catch(e){_._DumpException(e)}
}).call(this,this.default_PlayStoreUi);
// Google Inc.
